#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
NODES_ROOT="${ORTHUS_NODES_ROOT:-${HOME}/.orthus/nodes}"

die() {
  echo "error: $*" >&2
  exit 1
}

require_node() {
  local node="${1:-}"
  if [[ -z "${node}" ]]; then
    die "NODE required"
  fi
  printf '%s' "${node}"
}

node_env_profile() {
  printf '%s' "${ORTHUS_NODE_ENV:-${ORTHUS_NODE_PROFILE:-}}"
}

source_node_profile_env() {
  local node="$1"
  local stem="$2"
  local profile
  profile="$(node_env_profile)"
  if [[ -z "${profile}" || "${profile}" == "base" ]]; then
    return
  fi
  if [[ ! "${profile}" =~ ^[A-Za-z0-9_-]+$ ]]; then
    die "ORTHUS_NODE_ENV must be alphanumeric, dash, or underscore"
  fi
  local override_env="${NODES_ROOT}/${node}/${stem}.${profile}.env"
  if [[ ! -f "${override_env}" ]]; then
    die "ORTHUS_NODE_ENV=${profile} but ${override_env} is missing"
  fi
  # shellcheck disable=SC1090
  set -a
  source "${override_env}"
  set +a
}

sanitize_db_suffix() {
  local node="$1"
  local suffix
  suffix="$(printf '%s' "${node}" | tr '[:upper:]-' '[:lower:]_' | tr -cd 'a-z0-9_')"
  if [[ -z "${suffix}" ]]; then
    die "cannot derive DB suffix from node '${node}'"
  fi
  printf '%s' "${suffix}"
}

node_kind_for() {
  local node="$1"
  local override="${ORTHUS_NODE_KIND_OVERRIDE:-${NODE_KIND:-}}"
  if [[ -n "${override}" ]]; then
    if [[ "${override}" != "company" && "${override}" != "personal" ]]; then
      die "NODE_KIND must be company or personal"
    fi
    printf '%s' "${override}"
    return
  fi
  if [[ "${node}" == "company" ]]; then
    printf 'company'
  elif [[ "${node}" == company-* ]]; then
    printf 'company'
  else
    printf 'personal'
  fi
}

default_api_port_for() {
  local node="$1"
  local override="${ORTHUS_NODE_API_PORT:-${API_PORT:-}}"
  if [[ -n "${override}" ]]; then
    printf '%s' "${override}"
    return
  fi
  if [[ "${node}" == "company-staging" ]]; then
    printf '8920'
    return
  fi
  if [[ "${node}" == "personal-a-staging" ]]; then
    printf '8930'
    return
  fi
  if [[ "${node}" == "company" ]]; then
    printf '8820'
  else
    printf '8830'
  fi
}

default_web_port_for() {
  local node="$1"
  local override="${ORTHUS_NODE_WEB_PORT:-${WEB_PORT:-}}"
  if [[ -n "${override}" ]]; then
    printf '%s' "${override}"
    return
  fi
  if [[ "${node}" == "company-staging" ]]; then
    printf '3920'
    return
  fi
  if [[ "${node}" == "personal-a-staging" ]]; then
    printf '3930'
    return
  fi
  if [[ "${node}" == "company" ]]; then
    printf '3820'
  else
    printf '3830'
  fi
}

ensure_node_files() {
  local node="$1"
  local node_dir="${NODES_ROOT}/${node}"
  local node_env="${node_dir}/node.env"
  local web_env="${node_dir}/web.env"
  local kind db_suffix db_name api_port web_port
  local local_files_roots
  local codex_sessions_roots claude_sessions_roots
  local chat_exports_roots
  local email_exports_roots

  mkdir -p \
    "${node_dir}/wiki-store" \
    "${node_dir}/imports/notion" \
    "${node_dir}/imports/local-files" \
    "${node_dir}/imports/ai-sessions/codex" \
    "${node_dir}/imports/ai-sessions/claude" \
    "${node_dir}/imports/chat-exports" \
    "${node_dir}/imports/email-exports" \
    "${node_dir}/imports/email" \
    "${node_dir}/exports/promote-candidates" \
    "${node_dir}/logs"

  kind="$(node_kind_for "${node}")"
  db_suffix="$(sanitize_db_suffix "${node}")"
  db_name="orthus_${db_suffix}"
  api_port="$(default_api_port_for "${node}")"
  web_port="$(default_web_port_for "${node}")"
  local_files_roots=
  codex_sessions_roots=
  claude_sessions_roots=
  chat_exports_roots=
  email_exports_roots=
  # Default the chat/compile LLM to the local codex CLI (ChatGPT subscription)
  # for every fresh node so wiki distill/compile/answers run off the owner's
  # codex quota instead of metered API models. Existing node.env keeps its own
  # ORTHUS_LLM; the backfill below only supplies the codex command.
  local llm_default='cli'
  local llm_cli_cmd='codex exec --sandbox read-only --skip-git-repo-check -'
  if [[ "${kind}" == "personal" ]]; then
    local_files_roots='${ORTHUS_NODE_ROOT}/imports/local-files'
    codex_sessions_roots='${HOME}/.codex/sessions,${HOME}/.codex/history.jsonl,${ORTHUS_NODE_ROOT}/imports/ai-sessions/codex'
    claude_sessions_roots='${HOME}/.claude/projects,${HOME}/.claude/transcripts,${HOME}/.claude/history.jsonl,${ORTHUS_NODE_ROOT}/imports/ai-sessions/claude'
    chat_exports_roots='${ORTHUS_NODE_ROOT}/imports/chat-exports'
    email_exports_roots='${ORTHUS_NODE_ROOT}/imports/email-exports'
  fi

  if [[ ! -f "${node_env}" ]]; then
    cat > "${node_env}" <<EOF
# Generated by scripts/node/bootstrap_db.sh. Safe to edit.
ORTHUS_NODE_KIND=${kind}
ORTHUS_NODE_ID=${node}
ORTHUS_NODE_ROOT="\${HOME}/.orthus/nodes/${node}"
ORTHUS_NODE_DB=${db_name}

ORTHUS_PG_CONTAINER=orthus_pg
ORTHUS_PG_USER=orthus
ORTHUS_PG_PASS=orthus
ORTHUS_PG_HOST=localhost
ORTHUS_PG_PORT=5433
ORTHUS_RO_ROLE=orthus_ro

ORTHUS_PG_DSN="postgresql+psycopg://orthus:orthus@localhost:5433/\${ORTHUS_NODE_DB}"
ORTHUS_PG_DSN_READONLY="postgresql+psycopg://orthus_ro:orthus_ro@localhost:5433/\${ORTHUS_NODE_DB}"
ORTHUS_WIKI_STORE="\${ORTHUS_NODE_ROOT}/wiki-store"
ORTHUS_CORS_ORIGINS=http://localhost:${web_port},http://127.0.0.1:${web_port}

ORTHUS_API_PORT=${api_port}
ORTHUS_WEB_PORT=${web_port}
ORTHUS_WEB_API_BASE=http://localhost:${api_port}

ORTHUS_AUTH_MODE=demo
ORTHUS_AUTH_PUBLIC_BASE_URL=http://localhost:${api_port}
ORTHUS_AUTH_WEB_BASE_URL=http://localhost:${web_port}
ORTHUS_AUTH_COOKIE_NAME=orthus_session_${db_suffix}
ORTHUS_AUTH_COOKIE_SECURE=false
ORTHUS_AUTH_SESSION_SLIDING_DAYS=7
ORTHUS_AUTH_SESSION_ABSOLUTE_DAYS=30
ORTHUS_AUTH_SESSION_SECRET=
ORTHUS_AUTH_DEV_LOGIN_ENABLED=false
ORTHUS_GOOGLE_OAUTH_CLIENT_ID=
ORTHUS_GOOGLE_OAUTH_CLIENT_SECRET=
ORTHUS_CENTRAL_ADMIN_EMAILS=
ORTHUS_PERSONAL_OWNER_EMAIL=
ORTHUS_CENTRAL_READ_BASE_URL=
ORTHUS_CENTRAL_READ_TOKEN=
ORTHUS_CENTRAL_READ_TIMEOUT_MS=6000
ORTHUS_FEDERATION_SERVICE_TOKEN=
ORTHUS_FEDERATION_SERVICE_USER_ID=00000000-0000-4000-8000-000000000001

# Chat/LLM slot: wiki distill/compile, structured compile, answers.
ORTHUS_LLM=${llm_default}
ORTHUS_LLM_BASE_URL=https://api.openai.com/v1
ORTHUS_LLM_MODEL=gpt-4o-mini
ORTHUS_LLM_API_KEY=
ORTHUS_LLM_CLI_CMD='${llm_cli_cmd}'
ORTHUS_LLM_BEDROCK_API_KEY=
ORTHUS_LLM_BEDROCK_REGION=us-east-1
ORTHUS_LLM_BEDROCK_MODEL_ID=anthropic.claude-sonnet-4-6
ORTHUS_LLM_BEDROCK_INFERENCE_PREFIX=us
ORTHUS_LLM_BEDROCK_MAX_TOKENS=4096
ORTHUS_LLM_BEDROCK_TEMPERATURE=0
ORTHUS_LLM_BEDROCK_BASE_URL=

# Embedding slot: corpus/wiki retrieval indexes only. Independent from ORTHUS_LLM.
ORTHUS_EMBEDDING=mock
ORTHUS_EMBEDDING_API_KEY=
ORTHUS_EMBEDDING_BASE_URL=https://api.openai.com/v1
ORTHUS_EMBEDDING_MODEL=text-embedding-3-small
ORTHUS_EMBEDDING_DIMENSIONS=1024
ORTHUS_EMBEDDING_BEDROCK_API_KEY=
ORTHUS_EMBEDDING_BEDROCK_REGION=us-east-1
ORTHUS_EMBEDDING_BEDROCK_MODEL_ID=amazon.titan-embed-text-v2:0
ORTHUS_EMBEDDING_BEDROCK_FORMAT=titan_v2
ORTHUS_EMBEDDING_BEDROCK_INFERENCE_PREFIX=us
ORTHUS_EMBEDDING_BEDROCK_DIMENSIONS=1024
ORTHUS_EMBEDDING_BEDROCK_NORMALIZE=true
ORTHUS_EMBEDDING_BEDROCK_INPUT_TYPE=search_document
ORTHUS_EMBEDDING_BEDROCK_BATCH_SIZE=32
ORTHUS_EMBEDDING_BEDROCK_BASE_URL=

ORTHUS_CONN_NOTION_TOKEN=
ORTHUS_CONN_NOTION_TOKEN_1=
ORTHUS_CONN_NOTION_TOKEN_2=
ORTHUS_CONN_LOCAL_FILES_ROOTS="${local_files_roots}"
ORTHUS_CONN_LOCAL_FILES_EXTENSIONS=.md,.mdx,.txt,.json,.jsonl,.csv,.tsv
ORTHUS_CONN_LOCAL_FILES_MAX_BYTES=1048576
ORTHUS_CONN_CODEX_SESSIONS_ROOTS="${codex_sessions_roots}"
ORTHUS_CONN_CLAUDE_SESSIONS_ROOTS="${claude_sessions_roots}"
ORTHUS_CONN_AI_SESSIONS_MAX_BYTES=5242880
ORTHUS_CONN_AI_SESSIONS_MAX_FILES=200
ORTHUS_CONN_AI_SESSIONS_MAX_MESSAGES=200
ORTHUS_CONN_AI_SESSIONS_MAX_MESSAGE_CHARS=4000
ORTHUS_CONN_CHAT_EXPORTS_ROOTS="${chat_exports_roots}"
ORTHUS_CONN_CHAT_EXPORTS_MAX_BYTES=52428800
ORTHUS_CONN_CHAT_EXPORTS_MAX_MESSAGES=300
ORTHUS_CONN_CHAT_EXPORTS_MAX_MESSAGE_CHARS=4000
ORTHUS_CONN_EMAIL_EXPORTS_ROOTS="${email_exports_roots}"
ORTHUS_CONN_EMAIL_EXPORTS_MAX_BYTES=52428800
ORTHUS_CONN_EMAIL_EXPORTS_MAX_BODY_CHARS=12000
ORTHUS_CONN_GITHUB_TOKEN=
ORTHUS_CONN_GITHUB_REPOS=
ORTHUS_CONN_GITHUB_MAX_ITEMS=200
ORTHUS_CONN_SLACK_BOT_TOKEN=
ORTHUS_CONN_SLACK_CHANNELS=
ORTHUS_CONN_SLACK_MAX_MESSAGES=300
ORTHUS_SECRET_BACKEND=auto
EOF
    echo "created ${node_env}"
  fi

  if ! grep -q '^ORTHUS_CONN_LOCAL_FILES_ROOTS=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_LOCAL_FILES_ROOTS="%s"\n' "${local_files_roots}"
      printf 'ORTHUS_CONN_LOCAL_FILES_EXTENSIONS=.md,.mdx,.txt,.json,.jsonl,.csv,.tsv\n'
      printf 'ORTHUS_CONN_LOCAL_FILES_MAX_BYTES=1048576\n'
    } >> "${node_env}"
    echo "appended local-files connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_LLM_BEDROCK_REGION=' "${node_env}"; then
    {
      printf '# Chat/LLM slot: wiki distill/compile, structured compile, answers.\n'
      printf "ORTHUS_LLM_CLI_CMD='%s'\n" "${llm_cli_cmd}"
      printf 'ORTHUS_LLM_BEDROCK_API_KEY=\n'
      printf 'ORTHUS_LLM_BEDROCK_REGION=us-east-1\n'
      printf 'ORTHUS_LLM_BEDROCK_MODEL_ID=anthropic.claude-sonnet-4-6\n'
      printf 'ORTHUS_LLM_BEDROCK_INFERENCE_PREFIX=us\n'
      printf 'ORTHUS_LLM_BEDROCK_MAX_TOKENS=4096\n'
      printf 'ORTHUS_LLM_BEDROCK_TEMPERATURE=0\n'
      printf 'ORTHUS_LLM_BEDROCK_BASE_URL=\n'
    } >> "${node_env}"
    echo "appended bedrock llm env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_LLM_CLI_CMD=' "${node_env}"; then
    {
      printf "ORTHUS_LLM_CLI_CMD='%s'\n" "${llm_cli_cmd}"
    } >> "${node_env}"
    echo "appended cli llm env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_EMBEDDING_BEDROCK_REGION=' "${node_env}"; then
    {
      printf '# Embedding slot: corpus/wiki retrieval indexes only. Independent from ORTHUS_LLM.\n'
      printf 'ORTHUS_EMBEDDING_API_KEY=\n'
      printf 'ORTHUS_EMBEDDING_BASE_URL=https://api.openai.com/v1\n'
      printf 'ORTHUS_EMBEDDING_MODEL=text-embedding-3-small\n'
      printf 'ORTHUS_EMBEDDING_DIMENSIONS=1024\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_API_KEY=\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_REGION=us-east-1\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_MODEL_ID=amazon.titan-embed-text-v2:0\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_FORMAT=titan_v2\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_INFERENCE_PREFIX=us\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_DIMENSIONS=1024\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_NORMALIZE=true\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_INPUT_TYPE=search_document\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_BATCH_SIZE=32\n'
      printf 'ORTHUS_EMBEDDING_BEDROCK_BASE_URL=\n'
    } >> "${node_env}"
    echo "appended bedrock embedding env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_CODEX_SESSIONS_ROOTS=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_CODEX_SESSIONS_ROOTS="%s"\n' "${codex_sessions_roots}"
      printf 'ORTHUS_CONN_CLAUDE_SESSIONS_ROOTS="%s"\n' "${claude_sessions_roots}"
      printf 'ORTHUS_CONN_AI_SESSIONS_MAX_BYTES=5242880\n'
      printf 'ORTHUS_CONN_AI_SESSIONS_MAX_FILES=200\n'
      printf 'ORTHUS_CONN_AI_SESSIONS_MAX_MESSAGES=200\n'
      printf 'ORTHUS_CONN_AI_SESSIONS_MAX_MESSAGE_CHARS=4000\n'
    } >> "${node_env}"
    echo "appended ai-session connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_AI_SESSIONS_MAX_FILES=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_AI_SESSIONS_MAX_FILES=200\n'
    } >> "${node_env}"
    echo "appended ai-session max files env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_CHAT_EXPORTS_ROOTS=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_CHAT_EXPORTS_ROOTS="%s"\n' "${chat_exports_roots}"
      printf 'ORTHUS_CONN_CHAT_EXPORTS_MAX_BYTES=52428800\n'
      printf 'ORTHUS_CONN_CHAT_EXPORTS_MAX_MESSAGES=300\n'
      printf 'ORTHUS_CONN_CHAT_EXPORTS_MAX_MESSAGE_CHARS=4000\n'
    } >> "${node_env}"
    echo "appended chat-export connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_EMAIL_EXPORTS_ROOTS=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_EMAIL_EXPORTS_ROOTS="%s"\n' "${email_exports_roots}"
      printf 'ORTHUS_CONN_EMAIL_EXPORTS_MAX_BYTES=52428800\n'
      printf 'ORTHUS_CONN_EMAIL_EXPORTS_MAX_BODY_CHARS=12000\n'
    } >> "${node_env}"
    echo "appended email-export connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_GITHUB_TOKEN=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_GITHUB_TOKEN=\n'
      printf 'ORTHUS_CONN_GITHUB_REPOS=\n'
      printf 'ORTHUS_CONN_GITHUB_MAX_ITEMS=200\n'
    } >> "${node_env}"
    echo "appended github connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_CONN_SLACK_BOT_TOKEN=' "${node_env}"; then
    {
      printf 'ORTHUS_CONN_SLACK_BOT_TOKEN=\n'
      printf 'ORTHUS_CONN_SLACK_CHANNELS=\n'
      printf 'ORTHUS_CONN_SLACK_MAX_MESSAGES=300\n'
    } >> "${node_env}"
    echo "appended slack connector env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_SECRET_BACKEND=' "${node_env}"; then
    {
      printf 'ORTHUS_SECRET_BACKEND=auto\n'
    } >> "${node_env}"
    echo "appended secret backend env to ${node_env}"
  fi
  if ! grep -q '^ORTHUS_AUTH_MODE=' "${node_env}"; then
    {
      printf 'ORTHUS_AUTH_MODE=demo\n'
      printf 'ORTHUS_AUTH_PUBLIC_BASE_URL=http://localhost:%s\n' "${api_port}"
      printf 'ORTHUS_AUTH_WEB_BASE_URL=http://localhost:%s\n' "${web_port}"
      printf 'ORTHUS_AUTH_COOKIE_NAME=orthus_session_%s\n' "${db_suffix}"
      printf 'ORTHUS_AUTH_COOKIE_SECURE=false\n'
      printf 'ORTHUS_AUTH_SESSION_SLIDING_DAYS=7\n'
      printf 'ORTHUS_AUTH_SESSION_ABSOLUTE_DAYS=30\n'
      printf 'ORTHUS_AUTH_SESSION_SECRET=\n'
      printf 'ORTHUS_AUTH_DEV_LOGIN_ENABLED=false\n'
      printf 'ORTHUS_GOOGLE_OAUTH_CLIENT_ID=\n'
      printf 'ORTHUS_GOOGLE_OAUTH_CLIENT_SECRET=\n'
      printf 'ORTHUS_CENTRAL_ADMIN_EMAILS=\n'
      printf 'ORTHUS_PERSONAL_OWNER_EMAIL=\n'
      printf 'ORTHUS_CENTRAL_READ_BASE_URL=\n'
      printf 'ORTHUS_CENTRAL_READ_TOKEN=\n'
      printf 'ORTHUS_CENTRAL_READ_TIMEOUT_MS=6000\n'
      printf 'ORTHUS_FEDERATION_SERVICE_TOKEN=\n'
      printf 'ORTHUS_FEDERATION_SERVICE_USER_ID=00000000-0000-4000-8000-000000000001\n'
    } >> "${node_env}"
    echo "appended auth env to ${node_env}"
  fi

  if ! grep -q '^ORTHUS_CENTRAL_READ_BASE_URL=' "${node_env}"; then
    {
      printf 'ORTHUS_CENTRAL_READ_BASE_URL=\n'
      printf 'ORTHUS_CENTRAL_READ_TOKEN=\n'
      printf 'ORTHUS_CENTRAL_READ_TIMEOUT_MS=6000\n'
      printf 'ORTHUS_FEDERATION_SERVICE_TOKEN=\n'
      printf 'ORTHUS_FEDERATION_SERVICE_USER_ID=00000000-0000-4000-8000-000000000001\n'
    } >> "${node_env}"
    echo "appended federation read env to ${node_env}"
  fi

  if [[ ! -f "${web_env}" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "${node_env}"
    set +a
    cat > "${web_env}" <<EOF
# Generated by scripts/node/bootstrap_db.sh. Safe to edit.
NEXT_PUBLIC_API_BASE=${ORTHUS_WEB_API_BASE:-http://localhost:${ORTHUS_API_PORT:-8820}}
EOF
    echo "created ${web_env}"
  fi
}

load_node_env() {
  local node="$1"
  local node_env="${NODES_ROOT}/${node}/node.env"

  if [[ ! -f "${node_env}" ]]; then
    die "${node_env} missing; run make node-bootstrap NODE=${node}"
  fi

  # shellcheck disable=SC1090
  set -a
  source "${node_env}"
  set +a
  source_node_profile_env "${node}" "node"

  if [[ "${ORTHUS_NODE_ID:-}" != "${node}" ]]; then
    die "ORTHUS_NODE_ID=${ORTHUS_NODE_ID:-} does not match NODE=${node}"
  fi
  if [[ "${ORTHUS_NODE_KIND:-}" != "company" && "${ORTHUS_NODE_KIND:-}" != "personal" ]]; then
    die "ORTHUS_NODE_KIND must be company or personal"
  fi
  if [[ -z "${ORTHUS_NODE_DB:-}" ]]; then
    die "ORTHUS_NODE_DB missing in ${node_env}"
  fi
  if [[ -z "${ORTHUS_WIKI_STORE:-}" ]]; then
    die "ORTHUS_WIKI_STORE missing in ${node_env}"
  fi

  mkdir -p "${ORTHUS_WIKI_STORE}" "${ORTHUS_NODE_ROOT:-${NODES_ROOT}/${node}}/logs"
}

load_web_env() {
  local node="$1"
  local web_env="${NODES_ROOT}/${node}/web.env"
  if [[ -f "${web_env}" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "${web_env}"
    set +a
  fi
  source_node_profile_env "${node}" "web"
  export NEXT_PUBLIC_API_BASE="${NEXT_PUBLIC_API_BASE:-${ORTHUS_WEB_API_BASE:-http://localhost:${ORTHUS_API_PORT:-8820}}}"
}

assert_not_repo_wiki_store() {
  local resolved
  resolved="$(python3 - <<'PY'
import os
from pathlib import Path
print(Path(os.environ["ORTHUS_WIKI_STORE"]).expanduser().resolve())
PY
)"
  if [[ "${resolved}" == "${REPO_ROOT}/wiki-store" ]]; then
    die "ORTHUS_WIKI_STORE points at repo wiki-store; node store must be external"
  fi
}
